dist: bionic
language: python
cache: pip

stages:
  - lint
  - test

env:
  global:
    PYTHONUNBUFFERED=yes

matrix:
  include:
    - python: 3.6
      env: TOXENV=3.6
    - python: 3.7
      env: TOXENV=3.7
    - python: 3.8
      env: TOXENV=3.8
    - python: pypy3.6-7.3.1
      env: TOXENV=pypy3
    - python: 3.8
      env: TOXENV=flake8
      stage: lint
    - python: 3.8
      env: TOXENV=apicheck
      stage: lint
    - python: 3.8
      env: TOXENV=pydocstyle
      stage: lint

install:
    - pip install -U pip setuptools wheel | cat
    - pip install -U tox | cat
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
notifications:
  irc:
    channels:
      - "chat.freenode.net#celery"
    on_success: change
    on_failure: change
