os: linux
dist: xenial
language: python
cache: pip

addons:
  apt:
    update: true
    packages:
      - libgnutls-dev

env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - MATRIX_TOXENV=unit

stages:
  - test
  - integration
  - lint

_integration_job: &integration_job
    script:
        - tox -v -- -v
    services:
      - docker
    stage: integration

jobs:
  include:
    - python: 3.6
      env: TOXENV=3.6-unit
    - python: 3.7
      env: TOXENV=3.7-linux-unit
    - python: 3.8
      env: TOXENV=3.8-linux-unit
    - python: pypy3.6-7.3.1
      env: TOXENV=pypy3-unit
    - python: '3.8'
      env: TOXENV=flake8
      stage: lint
    - python: '3.8'
      env: TOXENV=apicheck
      stage: lint
    - python: '3.8'
      env: TOXENV=pydocstyle
      stage: lint
    - python: 3.6
      <<: *integration_job
      env: TOXENV=3.6-integration-py-amqp
    - python: 3.7
      <<: *integration_job
      env: TOXENV=3.7-linux-integration-py-amqp
    - python: 3.8
      <<: *integration_job
      env: TOXENV=3.8-linux-integration-py-amqp
    - python: pypy3.6-7.3.1
      <<: *integration_job
      env: TOXENV=pypy3-integration-py-amqp
    - python: 3.6
      <<: *integration_job
      env: TOXENV=3.6-integration-redis
    - python: 3.7
      <<: *integration_job
      env: TOXENV=3.7-linux-integration-redis
    - python: 3.8
      <<: *integration_job
      env: TOXENV=3.8-linux-integration-redis
    - python: pypy3.6-7.3.1
      <<: *integration_job
      env: TOXENV=pypy3-integration-redis

install:
    - pip --disable-pip-version-check install -U pip setuptools wheel | cat
    - pip --disable-pip-version-check install -U tox tox-docker | cat
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#celery"
    on_success: change
    on_failure: change
